
###
POST http://localhost:8002/plantillas/create
content-type: application/json

{
    "email"    : "cecilianazaretlopez@gmail.com",
    "name"     : "Cecilia López",
    "number"   : 11,
    "nic"      : "001-0985006-5",
    "address"  : "La Vereda #10, Res. Paraiso Palmas de Herrera, Apto. 3-G-1, Urb. Olimpo"
}


###
GET http://localhost:8002/plantillas/list
content-type: application/json

###
GET http://localhost:8002/plantillas/findbytipo/contrato
content-type: application/json
