@dueno = 627efe3b8a55c158e669107b

###
POST http://localhost:8002/publicaciones/publish
content-type: application/json

{
  "dueno": "{{dueno}}",
  "to" : "instagram",
  "image": "/Users/omarmojica/Proyectos/documi/backend/public/uploads/file.png",
  "url": "http://res.cloudinary.com/omarmojica/image/upload/v1657338810/documi/isbaf1btjqqsjtdfh815.png",
  "caption" : "Hyundai Grandeur 2012",
  "location" : "Santo Domingo, Dominican Republic",
  "show": true
}

###
POST http://localhost:8002/publicaciones/publish
content-type: application/json

{
  "dueno": "{{dueno}}",
  "to" : "instagram",
  "image": "/Users/omarmojica/proyectos/documi/documibackend/public/uploads/circulo.png",
  "url": "https://res.cloudinary.com/omarmojica/image/upload/v1657338810/documi/isbaf1btjqqsjtdfh815.png",
  "caption" : "Hyundai Grandeur 2012",
  "location" : "Santo Domingo, Dominican Republic",
  "show": true
}

###
POST http://localhost:8002/publicaciones/publish
content-type: application/json

{
  "dueno": "{{dueno}}",
  "to" : "marketplace",
  "image": "/Users/omarmojica/Proyectos/documi/backend/public/uploads/circulo.png",
  "url": "http://res.cloudinary.com/omarmojica/image/upload/v1657338810/documi/isbaf1btjqqsjtdfh815.png",
  "caption" : "Hyundai Grandeur 2012",
  "location" : "Santo Domingo, Dominican Republic",
  "year": "2012",
  "brand": "Hyundai",
  "model": "Grandeur",
  "show": true
}

###
POST http://localhost:8002/publicaciones/publish
content-type: application/json

{
  "dueno": "{{dueno}}",
  "to" : "marketplace",
  "image": "/Users/omarmojica/proyectos/documi/documibackend/public/uploads/circulo.png",
  "url": "http://res.cloudinary.com/omarmojica/image/upload/v1657338810/documi/isbaf1btjqqsjtdfh815.png",
  "caption" : "Hyundai Grandeur 2012",
  "location" : "Santo Domingo, Dominican Republic",
  "year": "2012",
  "brand": "Hyundai",
  "model": "Grandeur",
  "show": true
}

###
GET http://localhost:8002/publicaciones/list
content-type: application/json

###
POST http://localhost:8003/create-payment-intent
content-type: application/json

{"items": [{"id": "xl-tshirt"}]}

