
###
POST http://localhost:8000/usuarios/create
content-type: application/json

{
    "usuario"                : "usuariox3@gmail.com",
    "contrasena"             : "1234567",
    "nombre_empresa"         : "Empresa 3",
    "nombre"                 : "Juan Perez",
    "telefono"               : "809-848-2222",
    "whatsapp"               : "809-848-1111",
    "email"                  : "usuario3@gmail.com",
    "estado"                 : "activo"
}

###
GET http://localhost:8000/usuarios/listpop
content-type: application/json

###
POST http://localhost:8002/usuarios/login
content-type: application/json

{
  "email": "omarmojica@gmail.com",
  "password": "Romg2413"
}

###
POST http://localhost:8002/usuarios/create
content-type: application/json

{
    "nombre": "Cecilia Nazaret López 2",
    "telefono": "809-379-0955",
    "whatsapp": "829-447-3522",
    "nombre_empresa": "Creaciones de Ceci",
    "email": "cecilianazaretlopez@gmail.com",
    "password": "Cnla1324"
}

###
POST http://localhost:8000/usuarios/recoverpassword
content-type: application/json

{
    "nombre": "Cecilia Nazaret López 2",
    "email": "cecilianazaretlopez@gmail.com"
}
